/**
 * List of action types
 */
export const teachingstaffConstants = {
  TEACHINGSTAFF_REQUEST: 'TEACHINGSTAFF_REQUEST',
  TEACHINGSTAFF_SUCCESS: 'TEACHINGSTAFF_SUCCESS',
  TEACHINGSTAFF_FAILURE: 'TEACHINGSTAFF_FAILURE',
};
